t = 0:0.1:20;
F = 10*stepfun(t, 0);
F1 = 0;
F2 = 0;
subplot(2, 3, 1);
plot(t, F, 'r');
title('阶跃信号变化曲线');
xlabel('t');
ylabel('幅值');
grid on;
subplot(2, 3, 2);
plot(0:20, F1);
title('一阶导数变化曲线');
xlabel('t');
ylabel('一阶导数幅值');
grid on;
subplot(2, 3, 3);
plot(0:20, F2);
title('二阶导数变化曲线');
xlabel('t');
ylabel('二阶导数幅值');
grid on;
subplot(2, 3, 4);
a = real(fft(F));
plot(t, a);
grid on;
subplot(2, 3, 4);
Fs = 1000;
Ts=1/Fs;						
f=50;							
N=256;							
t1=(0:N-1)*Ts;
b = atan(t1);
NFFT=2^nextpow2(N);				
B=fft(b,NFFT);  
BB = abs(B);
f=(0:N-1)/(N*Ts);
plot(f, BB);
title('阶跃信号频域变化曲线');
xlabel('f/Hz');
ylabel('幅值');
grid on;
subplot(2, 3, 5);
Fs = 50;
Ts=1/Fs;					
f=50;							
N=256;							
t1=(0:N-1)*Ts;
b = atan(t1);
b1 = diff(b, 1);
NFFT=2^nextpow2(N);				
B1=fft(b1,NFFT); 
BB1 = abs(B1);
f=(0:N-1)/(N*Ts);
plot(f, BB1);
title('一阶导数频域变化曲线');
xlabel('f/Hz');
ylabel('一阶导数幅值');
grid on;
subplot(2, 3, 6);
Fs = 50;
Ts=1/Fs;				
f=50;					
N=256;						
t1=(0:N-1)*Ts;
b = atan(t1);
b2 = diff(b, 2);
NFFT=2^nextpow2(N);				
B2=fft(b2,NFFT);  
BB2 = abs(B2);
f=(0:N-1)/(N*Ts);
plot(f, BB2);
title('二阶导数频域变化曲线');
xlabel('f/Hz');
ylabel('二阶导数幅值');
grid on;

